### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by johndpope** [zsmb13/retrofit-meets-coroutines#1]
I use gradle build

I'm on vscode

I setup a new kotlin launch

![Screen Shot 2019-07-11 at 6 47 44 am](https://user-images.githubusercontent.com/289994/61003673-d7638400-a3a7-11e9-9384-f2f255c4b79e.png)

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "kotlin",
            "request": "launch",
            "name": "Kotlin Launch",
            "projectRoot": "${workspaceFolder}",
            "mainClass": "YourMainClassKt" // this doesn't seem to work with Main or anything else.
        }
    ]
}


```

seems like the directory structure 
co.zsmb.example needs to be mapped in folder structure for the class to be found??
master/src/main/kotlin >co > zsmb > example>

**Comment by johndpope** [comment]
doesn't seem to like the  Main.kt class on android studio either

![Screen Shot 2019-07-11 at 6 53 26 am](https://user-images.githubusercontent.com/289994/61004140-a46dc000-a3a8-11e9-9317-5c148562a6af.png)

**Comment by johndpope** [comment]
kotlinc src/main/kotlin/Main.kt
src/main/kotlin/Main.kt:3:12: error: unresolved reference: google
import com.google.gson.annotations.SerializedName
           ^
src/main/kotlin/Main.kt:4:8: error: unresolved reference: okhttp3
import okhttp3.OkHttpClient
       ^
src/main/kotlin/Main.kt:5:8: error: unresolved reference: retrofit2
import retrofit2.*
       ^
src/main/kotlin/Main.kt:6:8: error: unresolved reference: retrofit2
import retrofit2.converter.gson.GsonConverterFactory
       ^
src/main/kotlin/Main.kt:7:8: error: unresolved reference: retrofit2
import retrofit2.http.GET
       ^
src/main/kotlin/Main.kt:11:6: error: unresolved reference: SerializedName
    @SerializedName("rocket_name")
     ^
src/main/kotlin/Main.kt:16:6: error: unresolved reference: GET
    @GET("rockets")
     ^
src/main/kotlin/Main.kt:17:23: error: unresolved reference: Call
    fun getRockets(): Call<List<Rocket>>
                      ^
src/main/kotlin/Main.kt:21:6: error: unresolved reference: GET
    @GET("rockets")
     ^
src/main/kotlin/Main.kt:24:6: error: unresolved reference: GET
    @GET("rockets")
     ^
src/main/kotlin/Main.kt:25:39: error: unresolved reference: Response
    suspend fun getRocketsResponse(): Response<List<Rocket>>
                                      ^
src/main/kotlin/Main.kt:35:24: error: unresolved reference: OkHttpClient
    val okHttpClient = OkHttpClient()
                       ^
src/main/kotlin/Main.kt:37:20: error: unresolved reference: Retrofit
    val retrofit = Retrofit.Builder()
                   ^
src/main/kotlin/Main.kt:40:30: error: unresolved reference: GsonConverterFactory
        .addConverterFactory(GsonConverterFactory.create())
                             ^
src/main/kotlin/Main.kt:52:26: error: unresolved reference: Response
    val awaitedResponse: Response<List<Rocket>> = callApi.getRockets().awaitResponse()
                         ^
src/main/kotlin/Main.kt:54:33: error: cannot choose among the following candidates without completing type inference:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
        awaitedResponse.body()?.forEach(::println)
                                ^
src/main/kotlin/Main.kt:54:43: error: overload resolution ambiguity:
@InlineOnly public inline fun println(): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Any?): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Boolean): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Byte): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Char): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: CharArray): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Double): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Float): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Int): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Long): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Short): Unit defined in kotlin.io
        awaitedResponse.body()?.forEach(::println)
                                          ^
src/main/kotlin/Main.kt:66:19: error: unresolved reference: Response
    val response: Response<List<Rocket>> = api.getRocketsResponse()
                  ^
src/main/kotlin/Main.kt:68:26: error: cannot choose among the following candidates without completing type inference:
@HidesMembers public inline fun <T> Iterable<???>.forEach(action: (???) -> Unit): Unit defined in kotlin.collections
@HidesMembers public inline fun <K, V> Map<out ???, ???>.forEach(action: (Map.Entry<???, ???>) -> Unit): Unit defined in kotlin.collections
        response.body()?.forEach(::println)
                         ^
src/main/kotlin/Main.kt:68:36: error: overload resolution ambiguity:
@InlineOnly public inline fun println(): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Any?): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Boolean): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Byte): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Char): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: CharArray): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Double): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Float): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Int): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Long): Unit defined in kotlin.io
@InlineOnly public inline fun println(message: Short): Unit defined in kotlin.io
        response.body()?.forEach(::println)

**Comment by johndpope** [comment]
![Screen Shot 2019-07-11 at 7 05 39 am](https://user-images.githubusercontent.com/289994/61004887-5063db00-a3aa-11e9-8ae4-438c50f87ad6.png)


nesting the Main.kt into com.example subfolder (and renaming package to package com.example)
- now it can find it - but it just doesn't like it. 
Error: Unable to initialize main class com.example.MainKt 
Caused by: java.lang.NoClassDefFoundError: kotlin/coroutines/Continuation

**Comment by zsmb13** [comment]
Importing the project into Android Studio or IntelliJ IDEA is the easiest way to run it. You can create a run config for the `main` function by just clicking the run button next to it:

![image](https://user-images.githubusercontent.com/12054216/61172568-57dfdb80-a586-11e9-830b-21d6c246701a.png)

As for VSCode, running Gradle-based Kotlin projects in that environment has nothing to do with this project. Perhaps you should open an issue for that elsewhere if it's not working.

**Comment by johndpope** [comment]
Thanks
